# Generated by Django 5.1.5 on 2025-03-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='livedemo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
